### ISSUE TITLE
File Structure Needed

### ISSUE THREAD

**Issue by vandomej** [vandomej/PandEm#2]
Obviously we can't just shove the emulator into one file, plus we will be needing to interop with C files in the end, so we're guaranteed to need more files. I think we should initialize a discussion of what the final file layout of PandEm should be, and how we should separate the respective parts of code. I think we should look at the [video](https://www.youtube.com/watch?v=V6VP-2aIcSc) again first and then decide the structure.

**Comment by TrevorSpear** [comment]
We need to get on a white board and draw it out.

**Comment by vandomej** [comment]
Yeah true. Plus there is no rush as we go through this, I feel like im making it seem like there is, but I was just feeling like doing stuff for the repo earlier, so yeah. I won't be able to look at the video until after I finish work. I'm thinkin about just makin a diagram or something and posting it here and you can like modify it as you see fit.

**Comment by TrevorSpear** [comment]
I feel like if we don’t get on this it will only be a dream…. I do feel like we need to sit down and draw out what we need and keep a list and start filling out the list.

**Comment by TrevorSpear** [comment]
Can other people see these comments?

**Comment by vandomej** [comment]
Yeah true, I feel like the time when we should crunch down the hardest though is winter, but I will work on it as much as I can now. and yeah other people can see these, but its fine, no one will probably find this (except maybe employers we send this to)

**Comment by vandomej** [comment]
File structure didn't commit yeah. Here's the gist of what it will look like
```

Root
|
+ - main.rs
|
+ - nes
|    |
|    + - files.rs
|
+ - ui
|    |
|    + - files.c
|
+ - unit tests
     |
     + - unittests.rs
```
