### ISSUE TITLE
Decide on a graphics library to use for the UI.

### ISSUE THREAD

**Issue by TrevorSpear** [vandomej/PandEm#9]

**Comment by vandomej** [comment]
Alright, so i'm thinking about using OpenGL as a graphics library. The GUI part may be more difficult, but the general display window for the emulation will have a lot more control over with OpenGL.

**Comment by TrevorSpear** [comment]
I'm fine with that. More studying but that's what this project is for.

**Comment by vandomej** [comment]
Alright, that sounds good. Lets lock it in as OpenGL.
